export const toolPaths = [
  'supercommerce-api/list-payment-methods.js',
  'supercommerce-api/create-promo-code.js',
  'supercommerce-api/edit-promo-code.js',
  'supercommerce-api/list-order-status.js',
  'supercommerce-api/list-cities.js',
  'supercommerce-api/list-cancellation-reasons.js',
  'supercommerce-api/view-order.js',
  //'supercommerce-api/login.js',
  'supercommerce-api/activate-promo-code.js',
  'supercommerce-api/deactivate-customer.js',
  'supercommerce-api/view-customer.js',
  'supercommerce-api/deactivate-promo-code.js',
  'supercommerce-api/activate-customer.js',
  'supercommerce-api/view-promo-code.js',
  'supercommerce-api/edit-order-status.js',
  'supercommerce-api/list-products-for-create-order.js',
  'supercommerce-api/get-promo-code-list.js',
  'supercommerce-api/list-orders.js',
  'supercommerce-api/list-customers.js',
  'supercommerce-api/create-customer.js',
  'supercommerce-api/edit-customer.js',
  'supercommerce-api/create-address.js',
  'supercommerce-api/edit-order.js',
  'supercommerce-api/create-order.js',
  'supercommerce-api/get-all-category-dropdown.js',
  'supercommerce-api/get-all-brands-list-dropdown.js',
  'supercommerce-api/get-all-options-list-dropdown.js',
  'supercommerce-api/list-inventories.js',
  'supercommerce-api/upload-image.js',
  'supercommerce-api/get-category-list-paginated.js',
  'supercommerce-api/get-brands-list-paginated.js',
  'supercommerce-api/get-options-list-paginated.js',
  'supercommerce-api/get-details-product-by-id.js',
  'supercommerce-api/edit-option.js',
  'supercommerce-api/get-all-sub-categories-by-category-id-dropdown.js',
  'supercommerce-api/update-variant-product.js',
  'supercommerce-api/list-products-for-create-order.js',
  'supercommerce-api/create-variant-product.js',
  'supercommerce-api/create-brand.js',
  'supercommerce-api/create-option.js',
  'supercommerce-api/edit-brand.js',
  'supercommerce-api/get-product-list.js',
  'supercommerce-api/create-main-product.js',
  'supercommerce-api/create-category.js',
  'supercommerce-api/update-main-product.js',
  'supercommerce-api/edit-category-add-subcategory.js',
  'supercommerce-api/list-customer-groups.js',

  // Groups Management APIs
  'supercommerce-api/get-groups-list.js',
  'supercommerce-api/activate-group.js',
  'supercommerce-api/create-group.js',
  'supercommerce-api/update-group.js',
  'supercommerce-api/deactivate-group.js',
  'supercommerce-api/import-groups.js',
  'supercommerce-api/export-groups.js',

  // Custom Lists Management APIs
  'supercommerce-api/get-custom-lists.js',
  'supercommerce-api/create-custom-list.js',
  'supercommerce-api/delete-custom-list.js',
  'supercommerce-api/edit-custom-list.js',
  'supercommerce-api/save-custom-list.js',
  'supercommerce-api/export-custom-lists.js',
  'supercommerce-api/import-custom-lists.js',

];