name: Sync Postman Collection (Fixed)

on:
  push:
    paths:
      - 'postman/collections/*.json'
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  sync-tools:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate MCP tools from Postman collection
        id: generate
        run: |
          echo "Running tool generation script..."
          node scripts/generate-tools-from-postman.js > generation-output.txt 2>&1
          cat generation-output.txt

          # Check if any new or updated tools were generated
          if grep -q -E "(Generated.*new MCP tools|Auto-updated.*existing MCP tools)" generation-output.txt; then
            echo "new_tools=true" >> $GITHUB_OUTPUT
            echo "Tools were generated or updated"
          else
            echo "new_tools=false" >> $GITHUB_OUTPUT
            echo "No tools generated or updated"
          fi

      - name: Commit and Push Changes
        if: steps.generate.outputs.new_tools == 'true'
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add .

          COMMIT_MSG="feat: sync MCP tools with Postman collection

🤖 Automated tool synchronization
📅 Timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"

          git commit -m "$COMMIT_MSG" || echo "No changes to commit"
          git push origin master || git push origin main || echo "No changes to push"

      - name: Notify success
        if: steps.generate.outputs.new_tools == 'true'
        run: |
          echo "✅ Successfully synchronized MCP tools with Postman collection"
          echo "Changes have been committed and pushed"