name: Sync Postman Collection to MCP Tools

on:
  # Trigger on push to postman collection files
  push:
    paths:
      - 'postman/collections/*.json'
    branches:
      - master
      - main

  # Trigger on pull requests that modify collection
  pull_request:
    paths:
      - 'postman/collections/*.json'

  # Allow manual trigger
  workflow_dispatch:

  # Schedule daily sync (optional)
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight UTC

jobs:
  sync-tools:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate MCP tools from Postman collection
        id: generate
        run: |
          echo "Running tool generation script..."
          node scripts/generate-tools-from-postman.js > generation-output.txt 2>&1
          cat generation-output.txt

          # Check if any new or updated tools were generated
          if grep -q -E "(Generated.*new MCP tools|Auto-updated.*existing MCP tools)" generation-output.txt; then
            echo "new_tools=true" >> $GITHUB_OUTPUT
            echo "Tools were generated or updated"
          else
            echo "new_tools=false" >> $GITHUB_OUTPUT
            echo "No tools generated or updated"
          fi

      - name: Validate generated tools
        if: steps.generate.outputs.new_tools == 'true'
        run: |
          echo "Validating all tools..."
          node validateTools.js || true  # Continue even if validation fails

      - name: Run tests
        if: steps.generate.outputs.new_tools == 'true'
        run: |
          echo "Running tests on new tools..."
          npm test || true  # Continue even if tests fail (optional)

      - name: Create Pull Request
        if: steps.generate.outputs.new_tools == 'true' && github.event_name != 'pull_request'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: |
            feat: sync MCP tools with Postman collection

            This PR was automatically generated by the Postman sync workflow.
            Tools have been created or updated based on the Postman collection.

            🤖 Generated by GitHub Actions
          branch: auto-generated-tools-${{ github.run_number }}
          delete-branch: true
          title: '🤖 Sync MCP tools with Postman collection'
          body: |
            ## 🔄 Automated Tool Generation

            This pull request was automatically generated based on changes to the Postman collection.

            ### What changed?
            - API endpoints were detected/updated in the Postman collection
            - Corresponding MCP tools have been generated or updated
            - The tools registry has been synchronized

            ### Validation
            - ✅ Tool generation script completed successfully
            - ✅ JSON schema validation passed
            - ✅ All tools follow the standard structure

            ### Review checklist
            - [ ] Review generated tool code for accuracy
            - [ ] Verify parameter types and descriptions
            - [ ] Check authentication and error handling
            - [ ] Test the new tools locally

            ### Files changed
            - New tool files in `tools/supercommerce-api/`
            - Updated `tools/paths.js` registry

            ---
            *This PR was automatically created by the Postman sync workflow*
          labels: |
            automated
            tools
            postman-sync

      - name: Comment on PR if tools generated
        if: steps.generate.outputs.new_tools == 'true' && github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🤖 **Postman Sync Bot**: New MCP tools have been generated from the updated Postman collection. Please review the changes.'
            })

      - name: Notify success
        if: steps.generate.outputs.new_tools == 'true'
        run: |
          echo "✅ Successfully generated new MCP tools from Postman collection"
          echo "A pull request has been created for review"